<Project Sdk="Microsoft.NET.Sdk">

  <Import Project=".\..\ZendeskApi.Build\ZendeskApi.Commons.props" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
    <Description>A Zendesk Api Client for use with the ZendeskApi v2</Description>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Reflection" />
    <PackageReference Include="System.Reflection.Extensions" />
  </ItemGroup>

</Project>
